### PR TITLE
README.md: add troubleshooting instructions for use with scanbd

### PR DESCRIPTION
**Pull request by rrthomas**

### CODE REVIEW

**Comment by rrthomas** [comment]
Thanks very much for AirScan. Although I had to make a couple of changes to get it to work with my system, it was by far the easiest part of the process!

**Review by SimulPiscator — APPROVED** [review]

**Comment by SimulPiscator** [comment]
This is very helpful, thank you so much!

**Comment by watou** [comment]
Hating to be a negative nelly, but these instructions did not lead to peaceful coexistence between scanbd 1.5.1-6 and current build-from-source AirSane on my RPi 4 at latest RPi OS. Perhaps I misunderstood what successes are expected with these instructions.

airsaned will not successfully scan if scanbd is running. If scanbd service is started first, no scanners are found by airsaned. If scanbd started second, airsane scan proceeds as if possible but fails to start scanning.

I'm happy to provide any further info towards coexistence of both services functioning.  Thanks for AirSane and all contributors's efforts.

**Comment by SimulPiscator** [comment]
It seems that `scanimage` is not able to identify the scanner when running under the `saned` account while `scanbd` is active. I'll try to replicate that problem here and will come back to you.

**Comment by watou** [comment]
I also have these settings:
```
$ cat /etc/airsane/ignore.conf 
# ignore SANE eSCL backends to avoid loops
escl:.*
airscan:.*
```

**Comment by SimulPiscator** [comment]
> If you want to see what it can see, then you have to run:
> $ sudo SANE_CONFIG_DIR=/etc/scanbd scanimage -L

`scanimage` does not recognize my scanner when I run this.

**Comment by rrthomas** [comment]
> > If you want to see what it can see, then you have to run:
> > $ sudo SANE_CONFIG_DIR=/etc/scanbd scanimage -L
> 
> `scanimage` does not recognize my scanner when I run this.

It seems then that scanbd is not correctly set up. My understanding is that scanbd's `SANE_CONFIG_DIR` should find scanners in the way that a normal saned setup would; essentially you transfer your usual saned config to scanbd.

**Comment by SimulPiscator** [comment]
What I'm trying to do is to have `scanimage` connect to `scanbm` through the `net` backend configured at the SANE default location. I cannot get this to work.

**Comment by rrthomas** [comment]
> What I'm trying to do is to have `scanimage` connect to `scanbm` through the `net` backend configured at the SANE default location. I cannot get this to work.

I admit that it was not easy, but the Arch wiki is helpful: https://wiki.archlinux.org/title/Scanner_Button_Daemon

**Comment by SimulPiscator** [comment]
I got it working. I can call `scanimage -L` and it will list my scanner. Also, I can scan from my scanner.
`airsaned` works as well if started after `scanbd` (setup as suggested by @rrthomas).

**Pull request merged**
